Tests
Kondenko/yamblzweather pull request #3
Opened 2017-07-26 09:21 UTC by Mishkun

Added unit tests for key parts of buisness-logic and used across-project utils. Refactored some parts of logic to improve testability.
Added 2 instrumentation tests for about and settings screens

2017-07-28 23:03 UTC, Kondenko requested changes
Все круто, надо только пофиксить мелочи

2017-07-28 23:03 UTC, Kondenko commented on app/src/androidTest/java/com/kondenko/yamblzweather/ui/weather/AboutWindowTest.java
> +        onView(withId(R.id.about_text)).check(matches(withText("Мобилизация 2017 \n Владимир Конденко")));
Юзай строковый ресурс вместо хардкода

2017-07-28 23:03 UTC, Kondenko commented on app/src/main/java/com/kondenko/yamblzweather/utils/InclusiveRange.java
> +        if (max < min) {
Exception вместо свопа значений

2017-07-29 19:22 UTC, Kondenko approved these changes

2017-07-29 19:53 UTC, merged

2017-08-08 21:20 UTC, guliash commented on app/src/test/java/com/kondenko/yamblzweather/ui/weather/WeatherPresenterTest.java
> +    public void shouldLoadData() throws Exception {
Слишком большие тесты. Может разбить на более мелкие?

2017-08-08 21:20 UTC, guliash commented on app/src/test/java/com/kondenko/yamblzweather/ui/weather/WeatherPresenterTest.java
> +    public void setUp() {
Можно сюда и создание презентера.

2017-08-08 21:20 UTC, guliash commented on app/src/test/java/com/kondenko/yamblzweather/utils/SettingsManagerTest.java
> +public class SettingsManagerTest {
Имхо такой класс тестировать незачем.

2017-08-09 13:43 UTC, Mishkun commented on app/src/test/java/com/kondenko/yamblzweather/ui/weather/WeatherPresenterTest.java
> +    public void shouldLoadData() throws Exception {
А как это сделать, если в данном случае надо проверить, что презентер лез только туда, куда нужно и делал только то, что нужно?

2017-08-09 15:14 UTC, guliash commented on app/src/test/java/com/kondenko/yamblzweather/ui/weather/WeatherPresenterTest.java
> +    public void shouldLoadData() throws Exception {
Разбить на два теста - 1) проверяем что он лез только куда нужно 2) проверяем что делал только то, что нужно?)